import { CheckIcon as Check, MagnifyingGlassIcon as MagnifyingGlass } from 'phosphor-react-native';
import { Pressable, StyleSheet, Switch, Text, View } from 'react-native';

import { SettingsSubpage } from '@/components/settings/SettingsSubpage';
import { colors, onboardingFonts, radii } from '@/constants/theme';
import { useResearchSettings } from '@/features/settings/use-research-settings';

export default function ResearchSettingsScreen() {
  const settings = useResearchSettings();
  const choose = (consent: 'granted' | 'denied') => void settings.save(settings.enabled, consent);
  return <SettingsSubpage supporting="Research is optional and runs directly with the selected AI provider. It never goes through a Hmmmidea server." title="Research"><View style={styles.notice}><MagnifyingGlass color={colors.ink} size={20} weight="bold" /><Text style={styles.noticeText}>Provider-native grounding can receive a query derived from your transcript and relevant transcript context.</Text></View><View style={styles.row}><View style={styles.copy}><Text style={styles.label}>Use optional research</Text><Text style={styles.description}>Turn this on only after allowing provider-native research below.</Text></View><Switch accessibilityLabel="Use optional research" accessibilityState={{ busy: settings.saving, disabled: settings.saving }} disabled={settings.saving} onValueChange={(enabled) => void settings.setEnabled(enabled)} trackColor={{ false: colors.lineStrong, true: colors.primary }} value={settings.enabled} /></View><Text style={styles.sectionLabel}>GROUNDING CONSENT</Text><View accessibilityRole="radiogroup" style={styles.options}><ConsentOption active={settings.consent === 'granted'} body="A research request may send a derived query and relevant transcript context to the selected AI provider." disabled={settings.saving} label="Allow provider-native research" onPress={() => choose('granted')} /><ConsentOption active={settings.consent === 'denied'} body="Reports use the transcript only. No provider-native grounding request is made." disabled={settings.saving} label="Keep provider-native research off" onPress={() => choose('denied')} /></View>{settings.consent === 'unknown' ? <Text accessibilityRole="alert" style={styles.pending}>Choose an option before a research request can run.</Text> : null}{settings.message ? <Text accessibilityLiveRegion="polite" style={styles.message}>{settings.message}</Text> : null}</SettingsSubpage>;
}

function ConsentOption({ active, body, disabled, label, onPress }: { active: boolean; body: string; disabled: boolean; label: string; onPress(): void }) {
  return <Pressable accessibilityHint={body} accessibilityLabel={label} accessibilityRole="radio" accessibilityState={{ checked: active, disabled }} disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.option, active && styles.optionActive, pressed && styles.pressed, disabled && styles.disabled]}><View style={styles.optionCopy}><Text style={[styles.optionTitle, active && styles.activeText]}>{label}</Text><Text style={[styles.optionBody, active && styles.activeText]}>{body}</Text></View>{active ? <Check color={colors.ink} size={20} weight="bold" /> : null}</Pressable>;
}

const styles = StyleSheet.create({
  notice: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, padding: 16, borderRadius: radii.large, backgroundColor: colors.happySoft }, noticeText: { flex: 1, color: colors.ink, fontFamily: onboardingFonts.bodyRegular, fontSize: 13, lineHeight: 19 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 14, marginTop: 14, padding: 16, borderRadius: radii.large, backgroundColor: colors.canvas }, copy: { flex: 1, gap: 3 }, label: { color: colors.ink, fontFamily: onboardingFonts.bodySemiBold, fontSize: 15 }, description: { color: colors.inkMuted, fontFamily: onboardingFonts.bodyRegular, fontSize: 12, lineHeight: 17 },
  sectionLabel: { marginTop: 24, marginBottom: 8, color: colors.inkMuted, fontFamily: onboardingFonts.bodyBold, fontSize: 10, letterSpacing: 1 }, options: { gap: 10 }, option: { minHeight: 82, flexDirection: 'row', alignItems: 'center', gap: 12, padding: 16, borderRadius: radii.large, backgroundColor: colors.canvas }, optionActive: { backgroundColor: colors.primary }, optionCopy: { flex: 1, gap: 4 }, optionTitle: { color: colors.ink, fontFamily: onboardingFonts.bodySemiBold, fontSize: 14 }, optionBody: { color: colors.inkMuted, fontFamily: onboardingFonts.bodyRegular, fontSize: 12, lineHeight: 17 }, activeText: { color: colors.ink },
  pending: { marginTop: 12, color: colors.danger, fontFamily: onboardingFonts.bodySemiBold, fontSize: 12 }, message: { marginTop: 12, color: colors.inkMuted, fontFamily: onboardingFonts.bodyMedium, fontSize: 12 }, pressed: { opacity: 0.7 }, disabled: { opacity: 0.55 },
});
